# GitHub pages
# Deploys the documentation to github pages from the branch gh-pages.
---
name: GitHub Pages
on:
  push:
    branches:
      - master
      - ghp-test

jobs:
  ddsclidocumentation:
    name: Build the DDS CLI Documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Make dependencies available to Docker container
        run: |
          cat requirements.txt requirements-dev.txt > ./docs/requirements.txt
      - name: Build the HTML documentation
        uses: matthiaszepper/sphinx-action-v4@latest
        with:
          pre-build-command: |
            apt-get update && apt-get install -y build-essential libffi-dev
            pip install --upgrade pip setuptools wheel 
            pip install .
            pip install -r docs/requirements.txt
          build-command: "make dirhtml"
          docs-folder: "docs/"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/_build/dirhtml/
