# Pylint
# Checks for errors in Python code and encourages good Python coding patterns.
# ---
# Action failing?
# Manually fix the code producing warnings. Code must get 10/10.
---
name: Pylint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # If new Python versions are added, update pylint accordingly
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel
          pip install pylint==3.3.0
      - name: Analysing the code with pylint
        # Disable rule that limits to 5 the number of positional arguments
        run: |
          pylint --rcfile=.pylintrc \
            --disable=too-many-positional-arguments \
            -- $(git ls-files '*.py')
