# Rich-codex
# Rich-codex automatically generates "screenshots" / snippets of commands and their output.
# You can define the commands either in a MD file, but in our case the commands and snippets
# are defined in the file "../rich-codex.yml", which is automatically searched for by the tool.
# https://ewels.github.io/rich-codex/
---
name: Rich-codex
on: workflow_dispatch
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          skip_git_checks: "true"
          commit_changes: "true"
          clean_img_paths: docs/img/*.svg
