---
name: TestPyPi
on:
  pull_request:
    branches: [dev]
jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Build the distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish dist to TestPyPI
        if: github.repository == 'ScilifelabDataCentre/dds_cli'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
